<?php

declare(strict_types=1);

namespace Aurora\Taxonomy\Tests\Unit;

use Aurora\Entity\ContentEntityBase;
use Aurora\Entity\ContentEntityInterface;
use Aurora\Entity\EntityInterface;
use Aurora\Entity\FieldableInterface;
use Aurora\Taxonomy\Term;
use PHPUnit\Framework\TestCase;

/**
 * @covers \Aurora\Taxonomy\Term
 */
class TermTest extends TestCase
{
    // ---------------------------------------------------------------
    // Construction and interfaces
    // ---------------------------------------------------------------

    public function testImplementsInterfaces(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $this->assertInstanceOf(EntityInterface::class, $term);
        $this->assertInstanceOf(ContentEntityInterface::class, $term);
        $this->assertInstanceOf(FieldableInterface::class, $term);
        $this->assertInstanceOf(ContentEntityBase::class, $term);
    }

    public function testEntityTypeId(): void
    {
        $term = new Term(['vid' => 'tags']);

        $this->assertSame('taxonomy_term', $term->getEntityTypeId());
    }

    // ---------------------------------------------------------------
    // isNew
    // ---------------------------------------------------------------

    public function testIsNewWhenNoTidProvided(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $this->assertTrue($term->isNew());
    }

    public function testIsNotNewWhenTidProvided(): void
    {
        $term = new Term(['tid' => 1, 'vid' => 'tags', 'name' => 'PHP']);

        $this->assertFalse($term->isNew());
    }

    public function testEnforceIsNew(): void
    {
        $term = new Term(['tid' => 1, 'vid' => 'tags', 'name' => 'PHP']);
        $this->assertFalse($term->isNew());

        $term->enforceIsNew();
        $this->assertTrue($term->isNew());
    }

    // ---------------------------------------------------------------
    // UUID
    // ---------------------------------------------------------------

    public function testUuidAutoGenerated(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $uuid = $term->uuid();
        $this->assertNotEmpty($uuid);
        $this->assertMatchesRegularExpression(
            '/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/',
            $uuid
        );
    }

    public function testUuidPreservedWhenProvided(): void
    {
        $expected = '550e8400-e29b-41d4-a716-446655440000';
        $term = new Term(['vid' => 'tags', 'name' => 'PHP', 'uuid' => $expected]);

        $this->assertSame($expected, $term->uuid());
    }

    // ---------------------------------------------------------------
    // id() maps to tid
    // ---------------------------------------------------------------

    public function testIdReturnsTid(): void
    {
        $term = new Term(['tid' => 42, 'vid' => 'tags', 'name' => 'PHP']);

        $this->assertSame(42, $term->id());
    }

    public function testIdReturnsNullWhenNotSet(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $this->assertNull($term->id());
    }

    // ---------------------------------------------------------------
    // Name (label)
    // ---------------------------------------------------------------

    public function testGetName(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $this->assertSame('PHP', $term->getName());
    }

    public function testSetName(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $result = $term->setName('JavaScript');

        $this->assertSame('JavaScript', $term->getName());
        $this->assertSame($term, $result, 'setName() should return $this for fluent API');
    }

    public function testLabelMapsToName(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $this->assertSame('PHP', $term->label());
    }

    // ---------------------------------------------------------------
    // Vocabulary ID (bundle)
    // ---------------------------------------------------------------

    public function testGetVocabularyId(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $this->assertSame('tags', $term->getVocabularyId());
    }

    public function testBundleMapsToVid(): void
    {
        $term = new Term(['vid' => 'categories', 'name' => 'Science']);

        $this->assertSame('categories', $term->bundle());
    }

    // ---------------------------------------------------------------
    // Description
    // ---------------------------------------------------------------

    public function testGetDescriptionDefault(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $this->assertSame('', $term->getDescription());
    }

    public function testGetDescription(): void
    {
        $term = new Term([
            'vid' => 'tags',
            'name' => 'PHP',
            'description' => 'A general-purpose scripting language.',
        ]);

        $this->assertSame('A general-purpose scripting language.', $term->getDescription());
    }

    public function testSetDescription(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $result = $term->setDescription('Updated description');

        $this->assertSame('Updated description', $term->getDescription());
        $this->assertSame($term, $result, 'setDescription() should return $this for fluent API');
    }

    // ---------------------------------------------------------------
    // Weight
    // ---------------------------------------------------------------

    public function testGetWeightDefault(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $this->assertSame(0, $term->getWeight());
    }

    public function testGetWeight(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP', 'weight' => 5]);

        $this->assertSame(5, $term->getWeight());
    }

    public function testSetWeight(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $result = $term->setWeight(10);

        $this->assertSame(10, $term->getWeight());
        $this->assertSame($term, $result, 'setWeight() should return $this for fluent API');
    }

    public function testNegativeWeight(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP', 'weight' => -3]);

        $this->assertSame(-3, $term->getWeight());
    }

    // ---------------------------------------------------------------
    // Parent hierarchy
    // ---------------------------------------------------------------

    public function testGetParentIdDefaultIsNull(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $this->assertNull($term->getParentId());
    }

    public function testGetParentIdWithValue(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP', 'parent_id' => 5]);

        $this->assertSame(5, $term->getParentId());
    }

    public function testSetParentId(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $result = $term->setParentId(10);

        $this->assertSame(10, $term->getParentId());
        $this->assertSame($term, $result, 'setParentId() should return $this for fluent API');
    }

    public function testSetParentIdToNull(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP', 'parent_id' => 5]);

        $term->setParentId(null);

        $this->assertNull($term->getParentId());
    }

    // ---------------------------------------------------------------
    // isRoot
    // ---------------------------------------------------------------

    public function testIsRootWhenParentIsNull(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $this->assertTrue($term->isRoot());
    }

    public function testIsRootWhenParentIsZero(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP', 'parent_id' => 0]);

        $this->assertTrue($term->isRoot());
    }

    public function testIsNotRootWhenParentIsSet(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP', 'parent_id' => 5]);

        $this->assertFalse($term->isRoot());
    }

    public function testIsRootAfterSettingParentToNull(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP', 'parent_id' => 5]);
        $this->assertFalse($term->isRoot());

        $term->setParentId(null);
        $this->assertTrue($term->isRoot());
    }

    // ---------------------------------------------------------------
    // Published status
    // ---------------------------------------------------------------

    public function testIsPublishedDefaultsToTrue(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $this->assertTrue($term->isPublished());
    }

    public function testIsPublishedFalse(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP', 'status' => false]);

        $this->assertFalse($term->isPublished());
    }

    public function testSetPublished(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $result = $term->setPublished(false);

        $this->assertFalse($term->isPublished());
        $this->assertSame($term, $result, 'setPublished() should return $this for fluent API');
    }

    public function testSetPublishedToTrue(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP', 'status' => false]);

        $term->setPublished(true);

        $this->assertTrue($term->isPublished());
    }

    // ---------------------------------------------------------------
    // toArray
    // ---------------------------------------------------------------

    public function testToArrayContainsAllValues(): void
    {
        $term = new Term([
            'tid' => 1,
            'vid' => 'tags',
            'name' => 'PHP',
            'description' => 'A scripting language.',
            'weight' => 3,
            'parent_id' => 5,
            'status' => true,
        ]);

        $array = $term->toArray();

        $this->assertSame(1, $array['tid']);
        $this->assertSame('tags', $array['vid']);
        $this->assertSame('PHP', $array['name']);
        $this->assertSame('A scripting language.', $array['description']);
        $this->assertSame(3, $array['weight']);
        $this->assertSame(5, $array['parent_id']);
        $this->assertTrue($array['status']);
        $this->assertArrayHasKey('uuid', $array);
    }

    // ---------------------------------------------------------------
    // Fieldable interface (get/set/hasField)
    // ---------------------------------------------------------------

    public function testHasFieldForKnownFields(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $this->assertTrue($term->hasField('vid'));
        $this->assertTrue($term->hasField('name'));
        $this->assertTrue($term->hasField('description'));
        $this->assertTrue($term->hasField('weight'));
        $this->assertTrue($term->hasField('parent_id'));
        $this->assertTrue($term->hasField('status'));
    }

    public function testHasFieldForUnknownField(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $this->assertFalse($term->hasField('nonexistent'));
    }

    public function testGetAndSetField(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $term->set('custom_field', 'custom_value');

        $this->assertSame('custom_value', $term->get('custom_field'));
        $this->assertTrue($term->hasField('custom_field'));
    }

    // ---------------------------------------------------------------
    // Language
    // ---------------------------------------------------------------

    public function testLanguageDefaultsToEn(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP']);

        $this->assertSame('en', $term->language());
    }

    public function testLanguageCanBeSet(): void
    {
        $term = new Term(['vid' => 'tags', 'name' => 'PHP', 'langcode' => 'fr']);

        $this->assertSame('fr', $term->language());
    }

    // ---------------------------------------------------------------
    // Fluent API chaining
    // ---------------------------------------------------------------

    public function testFluentApiChaining(): void
    {
        $term = new Term(['vid' => 'tags']);

        $result = $term
            ->setName('PHP')
            ->setDescription('A language')
            ->setWeight(5)
            ->setParentId(10)
            ->setPublished(false);

        $this->assertSame($term, $result);
        $this->assertSame('PHP', $term->getName());
        $this->assertSame('A language', $term->getDescription());
        $this->assertSame(5, $term->getWeight());
        $this->assertSame(10, $term->getParentId());
        $this->assertFalse($term->isPublished());
    }
}
